num_cores: 1
core_freq_mhz: 800
core_stats_print_period_cycles: 100000

# ===== PE Array:  M(token) x N(output-ch) x P(input-ch) =====
pe_M: 8
pe_N: 8
pe_P: 1

# ===== 1D SIMD =====
simd_K: 8
simd_bit: 256

dram_type: ramulator2
dram_freq_mhz: 800
dram_channels: 1
dram_stats_print_period_cycles: 100000
ramulator_config_path: ../configs/ramulator2_configs/DDR4.yaml

icnt_type: booksim2
icnt_freq_mhz: 800

pytorchsim_functional_mode: 1
pytorchsim_timing_mode: 1

codegen_mapping_strategy: autotune
codegen_external_mapping_file: ''
codegen_autotune_max_retry: 10
codegen_autotune_template_topk: 4
codegen_compiler_optimization: all

# --- IMEM/WMEM/OMEM (3-way split SRAM, our NPU format) - 128KB each ---
imem_num_banks: 8
imem_sram_bitwidth: 256
imem_sram_depth: 512

wmem_num_banks: 8
wmem_sram_bitwidth: 256
wmem_sram_depth: 512

omem_num_banks: 8
omem_sram_bitwidth: 256
omem_sram_depth: 512
