num_cores: 1
vpu_num_lanes: 128
vpu_vector_length_bits: 256
vpu_spad_size_kb_per_lane: 128

# IMEM (Input Memory) - 128KB
imem_num_banks: 8
imem_sram_bitwidth: 256
imem_sram_depth: 512

# WMEM (Weight Memory) - 128KB
wmem_num_banks: 8
wmem_sram_bitwidth: 256
wmem_sram_depth: 512

# OMEM (Output Memory) - 128KB
omem_num_banks: 8
omem_sram_bitwidth: 256
omem_sram_depth: 512

pytorchsim_functional_mode: true
pytorchsim_timing_mode: false

codegen_mapping_strategy: heuristic
codegen_autotune_max_retry: 5
codegen_autotune_template_topk: 5

codegen_compiler_optimization: all

# TOGSim 설정
togsim_config_file: "/workspace/PyTorchSim/configs/npu_custom.yml"
