num_cores: 2
core_freq_mhz: 700
core_stats_print_period_cycles: 10000

# ===== PE Array:  M(token) x N(output-ch) x P(input-ch) =====
dataflow: os          # output-stationary (전 config OS 전환)
pe_M: 128
pe_N: 128
pe_P: 1

# ===== 1D SIMD =====
simd_K: 128
simd_bit: 256

dram_type: ramulator2
dram_freq_mhz: 700
dram_channels: 32
dram_stats_print_period_cycles: 10000
ramulator_config_path: ../configs/ramulator2_configs/HBM2_TPUv2.yaml

icnt_type: simple
icnt_latency_cycles: 10
icnt_freq_mhz: 700
icnt_injection_ports_per_core: 16

pytorchsim_functional_mode: 1
pytorchsim_timing_mode: 1

codegen_mapping_strategy: heuristic
codegen_external_mapping_file: ''
codegen_autotune_max_retry: 10
codegen_autotune_template_topk: 4
codegen_compiler_optimization: all

# --- IMEM/WMEM/OMEM (3-way split SRAM, our NPU format) - 128KB each ---
imem_num_banks: 8
imem_sram_bitwidth: 256
imem_sram_depth: 512

wmem_num_banks: 8
wmem_sram_bitwidth: 256
wmem_sram_depth: 512

omem_num_banks: 8
omem_sram_bitwidth: 256
omem_sram_depth: 512
